package gui;

import java.io.IOException;

import domein.DomeinController;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.VBox;

public class NavigatieContainerController extends BorderPane {

	@FXML
	private ImageView ivLogo;
	@FXML
	private ImageView ivPijl;
	@FXML
	private VBox vboxMenu;
	@FXML
	private Button btnDashboard;
	@FXML
	private Button btnCAT;
	@FXML
	private Button btnSDG;
	@FXML
	private Button btnMVO;
	@FXML
	private Button btnDS;
	@FXML
	private Button btnToggleMenu;

	private Image imgLogoLarge = new Image("IMAGES/LOGO.png");
	private Image imgLogoSmall = new Image("IMAGES/logoSmall.png");
	private boolean hasWideMenu = false;
	private DomeinController dc;

	public NavigatieContainerController() {
		this(new DomeinController());
	}

	public NavigatieContainerController(DomeinController dc) {
		FXMLLoader loader = new FXMLLoader(getClass().getResource("NavigatieContainer.fxml"));
		loader.setRoot(this);
		loader.setController(this);
		try {
			loader.load();
		} catch (IOException e) {
			throw new RuntimeException(e);
		}
		this.dc = dc;
		this.openDashboard(null);
	}

	// Event Listener on Button[#btnDashboard].onAction
	@FXML
	public void openDashboard(ActionEvent event) {
		this.setCenter(new DashboardSchermController(this.dc));
		this.enableAlleKnoppenInNavigatie();
		this.btnDashboard.setDisable(true);
	}

	// Event Listener on Button[#btnCAT].onAction
	@FXML
	public void openCAT(ActionEvent event) {
		this.setCenter(new CategorieSchermController(this.dc));
		this.enableAlleKnoppenInNavigatie();
		this.btnCAT.setDisable(true);
	}

	// Event Listener on Button[#btnSDG].onAction
	@FXML
	public void openSDG(ActionEvent event) {
		// TODO Autogenerated
		this.setCenter(new SdgSchermController(this.dc));
		this.enableAlleKnoppenInNavigatie();
		this.btnSDG.setDisable(true);
	}

	// Event Listener on Button[#btnMVO].onAction
	@FXML
	public void openMVO(ActionEvent event) {
		// TODO Autogenerated
		this.setCenter(new MVOdoelstellingController(this.dc));
		this.enableAlleKnoppenInNavigatie();
		this.btnMVO.setDisable(true);
	}

	// Event Listener on Button[#btnDS].onAction
	@FXML
	public void openDS(ActionEvent event) {
		// TODO Autogenerated
		this.setCenter(new DatasourceSchermController(this.dc));
		this.enableAlleKnoppenInNavigatie();
		this.btnDS.setDisable(true);
	}

	private void enableAlleKnoppenInNavigatie() {
		this.btnDashboard.setDisable(false);
		this.btnCAT.setDisable(false);
		this.btnSDG.setDisable(false);
		this.btnMVO.setDisable(false);
		this.btnDS.setDisable(false);
	}

	// Event Listener on Button[#btnToggleMenu].onAction
	@FXML
	public void toggleMenu(ActionEvent event) {
		this.hasWideMenu = !this.hasWideMenu;

		if (this.hasWideMenu) {
			this.vboxMenu.setPrefWidth(80);
			this.ivLogo.setImage(imgLogoSmall);
			this.ivLogo.setFitWidth(50);
			this.ivLogo.setFitHeight(50);
			this.btnCAT.setText("");
			this.btnSDG.setText("");
			this.btnMVO.setText("");
			this.btnDS.setText("");
			this.ivPijl.setRotate(180);
		} else {
			this.vboxMenu.setPrefWidth(300);
			this.ivLogo.setImage(imgLogoLarge);
			this.ivLogo.setFitWidth(200);
			this.ivLogo.setFitHeight(150);
			this.btnCAT.setText("Categorieën");
			this.btnSDG.setText("Sustainable Development Goals");
			this.btnMVO.setText("MVO-doelstellingen");
			this.btnDS.setText("Datasources");
			this.ivPijl.setRotate(360);
		}
	}
}
